language: generic
matrix:
  include:
  - os: linux
    dist: xenial
    sudo: required
    language: cpp
    compiler: gcc
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - g++-8
          - libatlas-base-dev
          - libblas-dev
  - os: osx
    osx_image: xcode10.2
    language: c++
    compiler: clang
before_install:
  - |
    if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      sudo ln -fs /usr/bin/gcc-8 /usr/local/bin/gcc
      sudo ln -fs /usr/bin/g++-8 /usr/local/bin/g++
    elif [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      brew update
      brew install openssl
      brew unlink openssl && brew link openssl --force
    fi
script:
  - set -e
  - |
    git clone https://github.com/Dekken/maiken -b master --depth 1 maiken
    [[ "${TRAVIS_OS_NAME}" == "osx" ]]   && make bsd -C maiken CXX=clang++
    [[ "${TRAVIS_OS_NAME}" == "linux" ]] && make nix -C maiken
    mv maiken/mkn .
    if [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then
      export MKN_LIB_LINK_LIB=1
      KLOG=3 ./mkn build -dtSa "-O2 -std=c++14" -l "-pthread -ldl" -p test run -b /usr/local/opt/openssl/include -B /usr/local/opt/openssl/lib
    elif [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
      ./mkn build -dtSa "-O2 -std=c++14 -fPIC" -l "-pthread -ldl" -p test run
    fi
