
git:
  depth: 3
matrix:
  include:
  - os: linux
    dist: bionic
    sudo: required
    compiler: gcc
    addons:
      apt:
        sources:
        - sourceline: 'ppa:ubuntu-toolchain-r/test'
        packages:
          - g++-8
    env:
      - MATRIX_EVAL="CC=gcc-8 && CXX=g++-8"
  - os: osx
    sudo: required
    osx_image: xcode11
    compiler: clang

before_install:
  - |
    if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      brew update
      brew install openssl
      brew unlink openssl && brew link openssl --force
    fi
script:
  - set -e
  - |
    export MKN_LIB_LINK_LIB="1" KUL_GIT_CO="--depth 3" KLOG="3"
    git clone https://github.com/Dekken/maiken -b master --depth 3 maiken
    if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      make bsd -C maiken CXX=clang++
      ./mkn build -dtSOa "-std=c++14" -l "-pthread -ldl" -p test run -b /usr/local/opt/openssl/include -B /usr/local/opt/openssl/lib
    fi
    if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      eval "${MATRIX_EVAL}"
      export CC CXX
      make nix -C maiken
      ./mkn build -dtSOa "-std=c++14 -fPIC" -l "-pthread -ldl" -p test run
    fi
