version: 0.1.{build}

branches:
  only:
    - master

max_jobs: 1

image:
- Visual Studio 2017

init:
  - git config --global core.autocrlf input

clone_depth: 1

hosts:
  queue-server: 127.0.0.1
  db.server.com: 127.0.0.2

platform: x64
configuration: Release

cache:
  - C:\ProgramData\chocolatey\bin -> appveyor.yml
  - C:\ProgramData\chocolatey\lib -> appveyor.yml

build_script:
  - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"
  - curl -o mkn.exe -L https://github.com/Dekken/maiken/raw/binaries/win10_x64/mkn.exe
  - SET MKN_CL_PREFERRED=1
  - SET KLOG=3
  # doesnt exist for somereason?
  - mkdir -p "C:\Program Files (x86)\Windows Kits\10\include\10.0.16299.0\cppwinrt"
  - C:\Python36-x64\Scripts\pip install conan
  - SET PYTHON=C:\Python36-x64\python.exe
  - mkn clean build -dtKOp usage
  - C:\Python36-x64\Scripts\pip install flawfinder
  - C:\Python36-x64\python C:\Python36-x64\Scripts\flawfinder .
