name: macos-latest

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2

    - name: "Build/Test" # contains slash so use quotes otherwise UB
      env:
        MKN_LIB_LINK_LIB: 1
      run: |
        brew install openssl
        wget https://github.com/PhilipDeegan/mkn/releases/download/latest/mkn_osx
        chmod +x mkn_osx
        KLOG=3 ./mkn_osx clean build run -dtOp test -a "-std=c++17 -fPIC" -b /usr/local/opt/openssl@3/include -B /usr/local/opt/openssl@3/lib
