name: windows-latest

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: "0 12 1 * *"

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4

    - uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: amd64

    - uses: actions/setup-python@v4
      with:
        python-version: '3.12.5'

    - name: "Build/Test"
      shell: cmd
      env:
        MKN_CL_PREFERRED: 1
        MKN_LIB_LINK_LIB: 1
      run: | # /bin/link interferes with cl/link.exe
        bash -c "rm /bin/link"
        bash -c "set -ex; python3 -m pip install wheel -U && python3 -m pip install conan -U && python3 -m conans.conan profile detect"
        bash -c "mkdir -p /c/Users/runneradmin/.conan && cp conan_remotes.json /c/Users/runneradmin/.conan/remotes.json"
        bash -c "curl -Lo mkn.exe https://github.com/mkn/mkn/releases/download/latest/mkn.exe"
        bash -c 'KLOG=3 ./mkn clean build -dtOp test -a "-EHsc -std:c++17"'
